force-app/main/default/objects/Order/fields/Generate_QR_Bill__c.field-meta.xml
<CustomField>
    <fullName>Generate_QR_Bill__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag used to request to generate QR Bill for an order</description>
    <label>Generate QR Bill</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <description>Date when Invoice was generated in Oracle.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Invoice Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Payor__c.field-meta.xml
<CustomField>
    <fullName>Payor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field points to the Payor</description>
    <label>Payor</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>contains</operation>
            <value>Payor, Pharmacy, Distributor, Clinic</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <formula>TEXT(Account.Preferred_Language__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Preferred Language</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Total_Gross_Price__c.field-meta.xml
<CustomField>
    <fullName>Total_Gross_Price__c</fullName>
    <formula>TotalAmount /*+  IF(VAT_TAX__c != 0.00, 0, Tax__c) */ + VAT_TAX__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Gross Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SClsCHQRBillGeneratorSchedule.cls
global class SClsCHQRBillGeneratorSchedule implements Schedulable {
    global void execute(SchedulableContext SC) {
        BClsGenerateQRBill batchClass = new BClsGenerateQRBill('SELECT Id, Preferred_Language__c, Total_Gross_Price__c, CurrencyIsoCode, Payor__r.Name, Account.Name, Account.AccountNumber, AccountId, BillingStreet, BillingCity, BillingPostalCode, BillingCountryCode, Invoice_Number__c, Invoice_Date__c FROM Order Where Generate_QR_Bill__c = true');
        Database.executebatch(batchClass, 1);
    }
}